### ISSUE TITLE
Unnecessary check of negative

### ISSUE THREAD

**Issue by miurahr** [takawitter/trie4j#42]
Hi, I found unnecessary check code in `o.t.doublearray.DoubleArray` and `o.t.doublearray.TailDoubleArray``#getChild` method.

```
   public DoubleArrayNode getChild(char c) {
            int code = charToCode[c];
            if (code == -1) return null;
            int nid = base[nodeId] + code;
```

Here `charToCode` is defined `char[]` and `char` is ranging from 0x0000 to 0xffff in language specification and never be negative.

I think it can be like 
```
        public DoubleArrayNode getChild(char c) {
            int nid = base[nodeId] + charToCode[c];
```

I found it when I check the project by SpotBugs, the above code [produce an error](https://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#int-bad-comparison-of-nonnegative-value-with-negative-constant-or-zero-int-bad-comparison-with-nonnegative-value).

**Comment by takawitter** [comment]
Thanks again!
I modified the code and added some tests.
