### ISSUE TITLE
Target Java version

### ISSUE THREAD

**Issue by miurahr** [takawitter/trie4j#45]
Why not update target Java version to Java 8?
We know Java 21 is just released in last September, and Java 1.7 has been out of support.
Contributors can use Java 8 features such as NIO2 when update.

**Comment by takawitter** [comment]
Several distributions have LTS versions. For example, Temurin provides Java8 LTS at least Nov 2026.
We can still start a new major version, such as 0.10.0, that uses the newest Java if you plan to add some features that depend on that.

**Comment by miurahr** [comment]
I don't have a plan to add a new feature, but just want to rewrite some test code which has a reference to wikipedia data.

**Comment by takawitter** [comment]
Now we have two active branches.
* 0.9.x - for 0.9.x versions that target Java7
* main - for 1.0.x and further versions that target Java8 or newer.

**Comment by miurahr** [comment]
clarified.
