### ISSUE TITLE
feature request: Support of Java Platform Module System (JPMS)

### ISSUE THREAD

**Issue by miurahr** [takawitter/trie4j#46]
Java 9 has new feature JPMS that was also known as Project jigsaw.
Because trie4j library has no dependency, it can be a leaf of software book of materials, it is valuable to support JPMS for me, at dependeents projects such as  mdict4j, stardict4j.

see.
https://central.sonatype.com/artifact/com.github.takawitter/trie4j/0.9.8/dependents

You can support JPMS with Multi-Release jar,  even when target Java is not 9.
see https://nipafx.dev/multi-release-jars-multiple-java-versions/

**Comment by takawitter** [comment]
moved to Java11 (next LTS release to Java8, that has the module support) and added module-info.java.
https://github.com/takawitter/trie4j/commit/e47f68265eeb32614751dc01fbd03ff872d66cbd
